Ot196 60 listado actividades
alkemyTech/OT196-Client pull request #23
Opened 2022-06-01 02:57 UTC by gerardodelascuevas

Incidencia https://alkemy-labs.atlassian.net/browse/OT196-60 
![image](https://user-images.githubusercontent.com/81906903/171318614-fdda220f-33de-4b23-ba14-8ff3a609f001.png)
![image](https://user-images.githubusercontent.com/81906903/171318657-4e2728bb-58f0-4c22-80df-2d1a2159dc47.png)
![image](https://user-images.githubusercontent.com/81906903/171318664-c50e034e-2946-4e82-93e3-6e1571fc66fe.png)
![image](https://user-images.githubusercontent.com/81906903/171318702-3b1a4ca4-677c-4bcc-ad36-6822869de677.png)
Los datos estan hardcodeados de un archivo que tambien subí, se necesita actualizar para que el componente trabaje, estoy atento a comentarios

2022-06-02 23:19 UTC, GauntStrelok requested changes

2022-06-02 23:19 UTC, GauntStrelok commented on src/Components/activities/ActivityCard.jsx
> +            !edit ?
Esto de alguna forma esta bueno, y de otra forma no tanto, yo te voy a dar el pie a vos aca para que decidas si lo dejas como esta o si lo cambias, te paso la info:
Para el edit de actividades tenemos un formulario de creacion/edicion que podemos usar en vez de esto.
Esto se ve funcional, pero rara vez los formularios inline se usan en apps reales, ya que se suelen ver feos

2022-06-02 23:19 UTC, GauntStrelok commented on src/Components/activities/ActivityList.jsx
> +                activitiesToShow ?
Que pasa si activitiesToShow es un array vacio?

2022-06-02 23:19 UTC, GauntStrelok commented
Ademas de estas consultas, hacer un pull de main para arreglar conflictos

2022-06-03 02:41 UTC, gerardodelascuevas commented on src/Components/activities/ActivityCard.jsx
> +            !edit ?
De acuerdo Pablo, gracias por el feedback, voy a modificar el componente de acuerdo a lo que me comentas

2022-06-06 11:11 UTC, merged