Ot196 57 edit user form
alkemyTech/OT196-Client pull request #24
Opened 2022-06-01 14:58 UTC by PedroBraude

https://alkemy-labs.atlassian.net/browse/OT196-57

### **Features**
- Add form and their respectives styles.
- Add Axios Petition for PUT user with req.params and edit with req.body.
- Add Axios Petition for GET user.

### **Evidence**

Default User One

![image](https://user-images.githubusercontent.com/32098492/171435478-9600c203-37f5-4365-84cd-a53cb1cca646.png)

After PUT User One

![image](https://user-images.githubusercontent.com/32098492/171435521-8821c0f1-4df5-448c-ac56-4033948a9494.png)

Validation Fields

![image](https://user-images.githubusercontent.com/32098492/171435344-3f6aa172-8dfa-4918-b311-371b8e337d45.png)

Invalidation Fields

![image](https://user-images.githubusercontent.com/32098492/171435430-10dc2d8a-7ffc-41b6-8cac-78ffa158ea9a.png)

### **Instructions for test*
**API:**
- In routes/users.js add:
```
// TEST GET without adminvalidation

router.get("/:id", async (req, res, next) => {
  const { id } = req.params;
  try {
    // Get data from DB
    const oneUser = await User.findByPk(id, {
      attributes: ["firstName", "lastName", "roleId"],
    });

    res.json(oneUser);
  } catch (e) {
    return res.status(500).json({ message: e.message });
  }
});

// TEST PUT user

router.put('/:id', async (req, res, next) => {
  const { id } = req.params;
  const { firstName, lastName, roleId} = req.body;

  try {
      const operacionActualizada = await User.update({
        firstName,
        lastName,
        roleId,
      },
      {returning: true,where: { id: id } })
      res.status(200).send(`La operación "${id}" fue modificada`)
  } catch (error) {
      next(error)
      res.status(400).send(`La operación no pudo modificarse ${error.message}`)
  }
})
```
**CLIENT**

- Change in EditUserForm          
`.put(`${REACT_APP_BACKEND}/users/:id`, { firstName: userData.firstName, lastName: userData.lastName, roleId: userData.roleId })`

instead

`.put(`${REACT_APP_BACKEND}/users/1`, { firstName: userData.firstName, lastName: userData.lastName, roleId: userData.roleId })`

and 

`.get(`${REACT_APP_BACKEND}/users/:id``

instead

`.get(`${REACT_APP_BACKEND}/users/1``

2022-06-02 23:22 UTC, GauntStrelok requested changes

2022-06-02 23:22 UTC, GauntStrelok commented on src/app/slice.js
> -import { createSlice } from "@reduxjs/toolkit";
Porque esta comentado este archivo?

2022-06-02 23:22 UTC, GauntStrelok commented on src/components/editUserForm/EditUserForm.js
> +          .get(`${REACT_APP_BACKEND}/users/2`)
Como se que ID poner aca?

2022-06-03 13:07 UTC, PedroBraude commented on src/app/slice.js
> -import { createSlice } from "@reduxjs/toolkit";
Me olvidé de descomentarlo, tenía problemas y para avanzar lo había comentado.

2022-06-03 13:36 UTC, PedroBraude commented on src/components/editUserForm/EditUserForm.js
> +          .get(`${REACT_APP_BACKEND}/users/2`)
Te referís al error de que deje hardcodeado? 

Porque venía siendo una duda de como va a llegar al id alli. A mi lo que se me ocurrió que cuando se toque el botón que te abra este formulario se cargué el id allí. 

Dicho eso me falta agregar una variable o estado donde se guarde el id de dicho elemento a modificar no?

2022-06-06 11:17 UTC, GauntStrelok commented on src/components/editUserForm/EditUserForm.js
> +          .get(`${REACT_APP_BACKEND}/users/2`)
ok, lo que se te ocurrio como seria, aplicalo, porque como esta ahora el componente, nadie podria usarlo para modificar a un usuario

2022-06-06 18:58 UTC, PedroBraude commented on src/components/editUserForm/EditUserForm.js
> +          .get(`${REACT_APP_BACKEND}/users/2`)
Pablo, se me ocurrio traer el id desde el store que tiene el authReducer que tiene todos los datos del usuario. Lo probé y funcionó. A su vez esto significaría trabajr con redux en gran parte del proyecto o por lo menos en las actividades relacionadas. Lo voy a charlar con los chicos.

2022-06-08 12:52 UTC, GauntStrelok commented on src/components/editUserForm/EditUserForm.js
> +          .get(`${REACT_APP_BACKEND}/users/2`)
Ojo, la idea esta bien cuando queres editar el usuario logueado, y que pasa cuando queres editar desde el backoffice?

2022-06-14 12:52 UTC, GauntStrelok commented
Cerrado porque se fue Pedro, y toma Eze la tarea

2022-06-14 12:52 UTC, closed without merging