[OT196-82]Screen Testimonials created
alkemyTech/OT196-Client pull request #25
Opened 2022-06-02 22:47 UTC by SantyR2001

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT196/boards/276?modal=detail&selectedIssue=OT196-82

I created screen testimonials, but this not connected to endpoint because it not exists.

![Captura de pantalla de 2022-06-02 19-00-50](https://user-images.githubusercontent.com/87712140/171750529-25ecf5db-89e4-413e-bcde-da3993af5302.png)

2022-06-06 11:18 UTC, GauntStrelok requested changes

2022-06-06 11:18 UTC, GauntStrelok commented on src/pages/ScreenTestimony.js
> +    let testimonials = [
Mira que tambien tiene datos del nombre de la persona, y de edicion y eliminacion, con el texto del testimonio, es suficiente para obtener estos datos?

2022-06-07 21:59 UTC, SantyR2001 commented
-add content to list
-add callback get for testimonials
-add function delete for button delete
-fix other errors from screen contact style

![Captura de pantalla de 2022-06-07 15-35-22](https://user-images.githubusercontent.com/87712140/172490034-dd3022b8-f320-4375-b2e9-dbad335ea4fe.png)

2022-06-07 22:00 UTC, SantyR2001 commented
![Captura de pantalla de 2022-06-06 19-03-02](https://user-images.githubusercontent.com/87712140/172490257-74ce7803-522c-4d58-84c4-5d39a262879a.png)

2022-06-08 12:54 UTC, merged